"""T044 — Extract legacy xlsx structure into a deterministic JSON fixture.

Spec 004 research §R-13 + tasks T044. One-shot inspection script that
loads ``data/silver/legacy/중간고사_분석결과.xlsx`` (the legacy LLM-era
output) and writes a JSON fixture to
``modules/immersio/tests/fixtures/legacy_xlsx_anchors.json`` capturing:

* Sheet names + display order.
* Per-sheet rough geometry (max_row, max_col).
* Per-sheet leading rows (title + memo + header row text) — the immersio
  ``xlsx_writer`` mirrors these so legacy_diff (US3) can compare by
  precise cell coordinate.
* Per-sheet chart anchors (from / to col + row) — empty list when the
  legacy sheet has no charts (the v1 anatomy export is fully tabular).

This is a *fixture* for tests, not runtime input. Run once whenever the
legacy structure changes; commit the JSON next to the script.

Spec FR-002 / SC-001 require legacy structure parity. Constitution III
forbids hard-coding volatile constants — anchor coordinates therefore
live in the fixture rather than in code.

Usage:
    uv run --package immersio python scripts/extract_legacy_xlsx_anchors.py \
        [--legacy data/silver/legacy/중간고사_분석결과.xlsx] \
        [--output modules/immersio/tests/fixtures/legacy_xlsx_anchors.json]

If the legacy xlsx is missing the script writes an *empty-but-valid*
fixture with ``"legacy_available": false`` and an explanatory ``notes``
field. Downstream tests must treat that branch as a soft skip (``T044``
guidance) so the pipeline still passes in environments without the
restricted legacy artifact.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

DEFAULT_LEGACY = Path("data/silver/legacy/중간고사_분석결과.xlsx")
DEFAULT_OUTPUT = Path("modules/immersio/tests/fixtures/legacy_xlsx_anchors.json")

_LEAD_ROWS_TO_CAPTURE = 6  # title + memo + header row + sample body rows


def _extract_chart_anchor(chart: Any) -> dict[str, Any]:
    anchor = chart.anchor
    out: dict[str, Any] = {"chart_type": type(chart).__name__}
    try:
        f = anchor._from
        t = anchor.to
        out["from"] = {"col": f.col, "row": f.row}
        out["to"] = {"col": t.col, "row": t.row}
    except AttributeError:
        out["anchor_repr"] = repr(anchor)
    title_txt: str | None = None
    if chart.title is not None:
        try:
            title_txt = chart.title.tx.rich.p[0].r[0].t  # type: ignore[union-attr]
        except (AttributeError, IndexError):
            title_txt = repr(chart.title)
    out["title"] = title_txt
    return out


def _extract_sheet(ws: Any) -> dict[str, Any]:
    lead_rows: list[list[Any]] = []
    for r in range(1, min(ws.max_row, _LEAD_ROWS_TO_CAPTURE) + 1):
        row_values = [ws.cell(r, c).value for c in range(1, ws.max_column + 1)]
        lead_rows.append(row_values)
    charts = [_extract_chart_anchor(ch) for ch in ws._charts]
    return {
        "max_row": ws.max_row,
        "max_col": ws.max_column,
        "lead_rows": lead_rows,
        "charts": charts,
    }


def extract(legacy_path: Path) -> dict[str, Any]:
    """Build the fixture dict for ``legacy_path``.

    Args:
        legacy_path: Path to the legacy xlsx. Missing file → soft fixture.

    Returns:
        Fixture dict with stable key ordering.
    """
    if not legacy_path.is_file():
        return {
            "legacy_available": False,
            "legacy_path": str(legacy_path),
            "notes": (
                "legacy xlsx not present in this environment — fixture writes "
                "the soft-skip branch. Run the extraction in the operator's "
                "environment after data/silver/legacy/중간고사_분석결과.xlsx "
                "lands. Spec 004 T044."
            ),
            "schema_version": "1.0.0",
            "sheets": [],
        }

    # Imported lazily so the script can be vendored into environments
    # without openpyxl (in which case the soft-skip branch above runs and
    # never reaches this import).
    from openpyxl import load_workbook

    wb = load_workbook(legacy_path, data_only=False)
    sheets: list[dict[str, Any]] = []
    for sn in wb.sheetnames:
        sheets.append(
            {
                "name": sn,
                "index": wb.sheetnames.index(sn),
                **_extract_sheet(wb[sn]),
            }
        )

    return {
        "legacy_available": True,
        "legacy_path": str(legacy_path),
        "schema_version": "1.0.0",
        "notes": (
            "Auto-generated by scripts/extract_legacy_xlsx_anchors.py. "
            "Edit the script and re-run rather than hand-editing this JSON."
        ),
        "sheets": sheets,
    }


def _serialise(value: Any) -> Any:
    """Replace non-JSON-serialisable types with stable string forms."""
    import datetime

    if isinstance(value, datetime.datetime):
        return value.isoformat()
    if isinstance(value, datetime.date):
        return value.isoformat()
    if isinstance(value, datetime.time):
        return value.isoformat()
    if isinstance(value, dict):
        return {k: _serialise(v) for k, v in value.items()}
    if isinstance(value, list):
        return [_serialise(v) for v in value]
    return value


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--legacy", type=Path, default=DEFAULT_LEGACY)
    p.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = p.parse_args(argv)

    fixture = extract(args.legacy)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    text = json.dumps(_serialise(fixture), indent=2, ensure_ascii=False, sort_keys=False)
    args.output.write_text(text + "\n", encoding="utf-8")
    print(f"wrote {args.output} ({len(fixture.get('sheets', []))} sheets)")
    if not fixture.get("legacy_available", False):
        print("  (legacy xlsx absent — soft-skip fixture written)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
